Repository Zatch-Team/Zatch_iOS, pull requests merged in 2022-09, with the labels that each got.

#16 #7: 약속잡기 SheetVC NavigationController embedded 통한 VC push 가능하게 함
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Chatting/ChattingRoomViewController.swift
  Zatch/domain/ViewControllers/Chatting/MakeMeetingSheetViewController.swift
  Zatch/global/Source/SheetNavigationViewController.swift
  Zatch/global/Source/SheetViewController.swift
Labels: 🎁 feat, 🌩 SSOOYA

#17 #7: SearchAddressResultVC MVVM 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/ChattingCells/SearchAddressResultTableViewCell.swift
  Zatch/domain/ViewControllers/Chatting/ChattingRoomViewController.swift
  Zatch/domain/ViewControllers/Chatting/MakeMeetingSheetViewController.swift
  Zatch/domain/ViewControllers/Chatting/SearchAddressResultBottomSheet.swift
  Zatch/domain/ViewModels/ChattingViewModels/SearchAddressResusltViewModel.swift
  Zatch/domain/Views/ChattingView/SearchAddressResultView.swift
  Zatch/global/Source/SheetViewController.swift
Labels: 🎁 feat, 🌩 SSOOYA

#26 #7: MeetingSheetVC 부모, MakeMeetingSheet & ModifyMeetingSheet 자식으로 상속 …
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Chatting/MeetingSheetViewController.swift
  Zatch/domain/ViewControllers/Chatting/ModifyMeetingSheetViewController.swift
  Zatch/domain/ViewModels/ChattingViewModels/MakeMeetingSheetViewModel.swift
  Zatch/domain/ViewModels/ChattingViewModels/MeetingSheetViewModel.swift
  Zatch/domain/ViewModels/ChattingViewModels/ModifyMeetingSheetViewModel.swift
  Zatch/domain/Views/ChattingView/MakeMeetingSheetView.swift
  Zatch/domain/Views/ChattingView/MeetingSheetView.swift
  Zatch/domain/Views/ChattingView/ModifyMeetingSheetView.swift
Labels: 🎁 feat, 🌩 SSOOYA

#27 #7: MakeMeetingSheet View, VC 분리 및 UI 공통 요소 class로 관리, UINavigationController extension 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Chatting/MakeMeetingSheetViewController+Layout.swift
  Zatch/domain/ViewControllers/Chatting/MakeMeetingSheetViewController.swift
  Zatch/domain/ViewControllers/Chatting/MeetingSheetViewController.swift
  Zatch/domain/ViewControllers/Chatting/SearchAddressResultBottomSheet.swift
  Zatch/domain/Views/ChattingView/MakeMeetingSheetView.swift
  Zatch/domain/Views/ChattingView/MeetingSheetView.swift
  Zatch/global/Resource/extenstion/UINavigationControllerViewController.swift
Labels: 🎁 feat, 🌩 SSOOYA

#28 #7: ModiftMeeting UI 구현 및 InfoAlert 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Chatting/ChattingRoomViewController.swift
  Zatch/domain/ViewControllers/Chatting/MakeMeetingSheetViewController.swift
  Zatch/domain/ViewControllers/Chatting/ModifyMeetingSheetViewController.swift
  Zatch/domain/Views/ChattingView/MakeMeetingSheetView.swift
  Zatch/domain/Views/ChattingView/MeetingSheetView.swift
  Zatch/domain/Views/ChattingView/ModifyMeetingSheetView.swift
  Zatch/global/Source/Alert/AlertViewController.swift
  Zatch/global/Source/Alert/BasicAlertViewController.swift
  Zatch/global/Source/Alert/InfoAlertViewController.swift
Labels: 🎁 feat, 🌩 SSOOYA

#34 #7: KakaoLocalDataManager 파일 추가 및 카카오 로컬 API 통해 주소 검색 결과 가져오기
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Services/Chatting/KakaoLocalDataManager/KakaoLocalDataManager.swift
  Zatch/domain/Services/Chatting/KakaoLocalDataManager/KakaoLocalModel.swift
  Zatch/domain/ViewControllers/Chatting/SearchAddressBottomSheet.swift
  Zatch/domain/ViewControllers/Chatting/SearchAddressResultBottomSheet.swift
  Zatch/global/Resource/Const.swift
Labels: 🎁 feat, 🌩 SSOOYA

#36 issue #7 기능 구현, #35 오류 수정
  Zatch/domain/Cells/ChattingCells/SearchAddressResultTableViewCell.swift
  Zatch/domain/Services/Chatting/KakaoLocalDataManager/KakaoLocalDataManager.swift
  Zatch/domain/ViewControllers/Chatting/SearchAddressResultBottomSheet.swift
  Zatch/global/Resource/extenstion/UINavigationControllerViewController.swift
Labels: ⚠️ bug, 🎁 feat, ✏️ fix, 🌩 SSOOYA

#38 #37: AlertVC 상속관계 재정의 및 파일 정리
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/ChattingCells/ChattingListTableViewCell.swift
  Zatch/domain/ViewControllers/Chatting/ChattingRoomViewController.swift
  Zatch/domain/ViewControllers/Register/DeleteImageDetailViewController.swift
  Zatch/domain/Views/ChattingView/MakeMeetingSheetView.swift
  Zatch/global/Resource/CommonSource/UIButton/PurpleButton.swift
  Zatch/global/Source/Alert/AlertViewController.swift
  Zatch/global/Source/Alert/BasicAlertViewController.swift
  Zatch/global/Source/Alert/CancelAlertViewController.swift
  Zatch/global/Source/Alert/InfoAlertViewController.swift
  Zatch/global/Source/Alert/MessageAlertViewController.swift
Labels: 💎 refactor, 🌩 SSOOYA

#44 마이페이지의 내정보 페이지 UI 구현
  Zatch.xcodeproj/project.pbxproj
  Zatch.xcworkspace/xcuserdata/gomin.xcuserdatad/UserInterfaceState.xcuserstate
  Zatch/Assets.xcassets/Icons/pin.imageset/Contents.json
  Zatch/Assets.xcassets/Icons/pin.imageset/pin.svg
  Zatch/Assets.xcassets/Icons/setting.imageset/Contents.json
  Zatch/Assets.xcassets/Icons/setting.imageset/setting.svg
  Zatch/Assets.xcassets/Images/certificationBanner.imageset/Contents.json
  Zatch/Assets.xcassets/Images/certificationBanner.imageset/certificationBanner.svg
  Zatch/domain/Cells/MypageCells/CertificationBannerTableViewCell.swift
  Zatch/domain/Cells/MypageCells/MyInfoTableViewCell.swift
  Zatch/domain/Cells/MypageCells/MyZatchStatisticTableViewCell.swift
  Zatch/domain/Cells/MypageCells/MypageSettingTableViewCell.swift
  Zatch/domain/Cells/MypageCells/TownSettingTableViewCell.swift
  Zatch/domain/ViewControllers/Mypage/MypageViewController.swift
  Zatch/domain/ViewControllers/Profile/ProfileViewController.swift
  Zatch/domain/Views/MypageView/MypageView.swift
  Zatch/global/Source/TabBarViewController.swift
Labels: 🎁 feat

#45 #43: 동네인증 소스 파일 및 이미지 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch/Assets.xcassets/town_alert.imageset/Contents.json
  Zatch/Assets.xcassets/town_alert.imageset/Place Image.svg
  Zatch/Assets.xcassets/town_splash.imageset/Asset 6@2x 1.svg
  Zatch/Assets.xcassets/town_splash.imageset/Contents.json
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/ViewControllers/Town/SearchTownViewController.swift
  Zatch/domain/ViewControllers/Town/SplashTownViewController.swift
  Zatch/domain/Views/TownView/MapTownView.swift
  Zatch/domain/Views/TownView/SearchTownView.swift
  Zatch/domain/Views/TownView/SplashTownView.swift
Labels: 🎁 feat, 🌩 SSOOYA

#47 #43: 동네 설정 관련 UI 파일 상속관계 정리 및 공통 리소스 파일 정리
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/TownCells/MyTownTagCollectionViewCell.swift
  Zatch/domain/ViewControllers/Register/CheckRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/FirstRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/SecondRegisterViewController.swift
  Zatch/domain/ViewControllers/Search/FindSearchViewController.swift
  Zatch/domain/ViewControllers/Search/MySearchViewController.swift
  Zatch/domain/ViewControllers/Search/ResultSearchViewController.swift
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/ViewControllers/Town/SearchTownViewController.swift
  Zatch/domain/Views/ChattingView/MeetingSheetView.swift
  Zatch/domain/Views/ChattingView/SearchAddressView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/domain/Views/TownView/MapTownView.swift
  Zatch/domain/Views/TownView/SearchTownView.swift
  Zatch/domain/Views/TownView/SplashTownView.swift
  Zatch/global/Resource/CommonSource/LocationSearchTextField.swift
  Zatch/global/Resource/CommonSource/UIButton/PurpleButton.swift
  Zatch/global/Resource/CommonSource/UIButton/SearchCateogryDotButton.swift
  Zatch/global/Resource/extenstion/UIButton.swift
Labels: 🎁 feat, 🎀 style, 💎 refactor, 💬 chore, 🌩 SSOOYA

#48 [fix] Excluded Architectures에 arm64 추가
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Zatch.xcodeproj/project.pbxproj
  Zatch.xcworkspace/xcuserdata/gomin.xcuserdatad/UserInterfaceState.xcuserstate
  Zatch/domain/Views/GominStoryboard.storyboard
Labels: ✏️ fix

#49 #43: 동네 인증 마커 아이콘 Asset 추가
  Zatch/Assets.xcassets/Town/map_marker.imageset/Contents.json
  Zatch/Assets.xcassets/Town/map_marker.imageset/Map.svg
  Zatch/Assets.xcassets/Town/town_splash.imageset/Asset 6@2x 1.svg
  Zatch/Assets.xcassets/Town/town_splash.imageset/Contents.json
  Zatch/domain/Cells/TownCells/MyTownTagCollectionViewCell.swift
  Zatch/domain/ViewControllers/Town/SearchTownViewController.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/domain/Views/TownView/SearchTownView.swift
  Zatch/global/Source/Category/CategoryBottomSheet.swift
Labels: 🎁 feat, 🌩 SSOOYA

#50 #43: 동네 설정 지도 관련 파일 추가 및 주소 정보 가공 통한 동네 정보 수집
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/Views/TownView/MapTownView.swift
  Zatch/global/Resource/Zatch-Bridging-Header.h
  Zatch/global/Resource/extenstion/String.swift
  Zatch/global/Source/Alert/MapAlertViewController.swift
Labels: 🎁 feat, 🌩 SSOOYA

#53 Info.plist 파일 수정 및 KakaoLocalDataManager 파일 경로 수정
  Zatch.xcodeproj/project.pbxproj
  Zatch.xcodeproj/xcuserdata/vertigo.xcuserdatad/xcschemes/xcschememanagement.plist
  Zatch/Info.plist
  Zatch/domain/Services/KakaoDataManager/KakaoLocalDataManager.swift
  Zatch/domain/ViewControllers/Chatting/SearchAddressResultBottomSheet.swift
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/global/Source/Alert/MapAlertViewController.swift
Labels: 🎁 feat, 💬 chore, 🌩 SSOOYA

#54 #43: KakaoLocationAddressModel 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Models/TownModels/KakaoLocationAddressModel.swift
  Zatch/domain/Services/KakaoDataManager/KakaoLocalDataManager.swift
  Zatch/domain/ViewControllers/Chatting/SearchAddressResultBottomSheet.swift
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
Labels: 🎁 feat, 🌩 SSOOYA

#58 마이페이지 차단된 사용자 파일 추가 및 카카오 로컬 api model 오류 수정
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/MypageCells/MyPage/BlockUserTableViewCell.swift
  Zatch/domain/Models/TownModels/KakaoLocationAddressModel.swift
  Zatch/domain/Services/KakaoDataManager/KakaoLocalDataManager.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/BlockUserViewController.swift
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/Views/ChattingView/MeetingSheetView.swift
  Zatch/domain/Views/MypageView/Mypage/BlockUserView.swift
  Zatch/global/Source/SheetNavigationViewController.swift
  Zatch/global/Source/SheetViewController.swift
Labels: 🎁 feat, ✏️ fix, 🌩 SSOOYA

#60 close #59: BaseVC 파일 상속 정리 및 적용
  Pods/Pods.xcodeproj/xcuserdata/vertigo.xcuserdatad/xcschemes/xcschememanagement.plist
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/MypageCells/MyPage/BlockUserTableViewCell.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/BlockUserViewController.swift
  Zatch/domain/ViewControllers/Register/CheckRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/FirstRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/SecondRegisterViewController.swift
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/Views/MypageView/Mypage/BlockUserView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/global/Source/BaseCenterTitleViewController.swift
  Zatch/global/Source/BaseLeftTitleViewController.swift
  Zatch/global/Source/BaseViewController.swift
Labels: 🎀 style, 💎 refactor, 🌩 SSOOYA

#61 close #55: MapAlert 상속 관계 정리 및 파일/코드 정리
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/global/Source/Alert/MapAlertViewController.swift
  Zatch/global/Source/Alert/MeetingMapAlertViewController.swift
  Zatch/global/Source/Alert/TownMapAlertViewController.swift
Labels: 💎 refactor, 🌩 SSOOYA

#64 #63: map 관련 파일 부모 클래스 KakaoMap.. 이름으로 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch.xcworkspace/xcuserdata/vertigo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Zatch/domain/Models/TownModels/KakaoLocationAddressModel.swift
  Zatch/domain/Services/KakaoDataManager/KakaoLocalDataManager.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/MakeMeetingSheetViewController.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/MapMeetingViewController.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/ModifyMeetingSheetViewController.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/SearchAddressBottomSheet.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/SearchAddressResultBottomSheet.swift
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/Views/ChattingView/AppointmentView/MakeMeetingSheetView.swift
  Zatch/domain/Views/ChattingView/AppointmentView/MapMeetingView.swift
  Zatch/domain/Views/ChattingView/AppointmentView/MeetingSheetView.swift
  Zatch/domain/Views/ChattingView/AppointmentView/ModifyMeetingSheetView.swift
  Zatch/domain/Views/ChattingView/AppointmentView/SearchAddressResultView.swift
  Zatch/domain/Views/ChattingView/AppointmentView/SearchAddressView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/global/Source/Alert/InfoAlertViewController.swift
  Zatch/global/Source/Alert/MapAlertViewController.swift
  Zatch/global/Source/Map/KakaoMapView.swift
  Zatch/global/Source/Map/KakaoMapViewController.swift
Labels: 🎁 feat, 💎 refactor, 💬 chore, 🌩 SSOOYA

#65 MapVC 자식 클래스 코드 작성
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Models/ChattingModels/KakaoLocalMeetingModel.swift
  Zatch/domain/Models/ChattingModels/KakaoLocalTownModel.swift
  Zatch/domain/Services/KakaoDataManager/KakaoLocalDataManager.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/MapMeetingViewController.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/SearchAddressBottomSheet.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/SearchAddressResultBottomSheet.swift
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/Views/ChattingView/AppointmentView/MapMeetingView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/domain/Views/TownView/MapTownView.swift
  Zatch/global/Resource/CommonSource/UIButton/PurpleButton.swift
  Zatch/global/Source/Map/KakaoMapView.swift
  Zatch/global/Source/Map/KakaoMapViewController.swift
Labels: 🎁 feat, 💎 refactor, 💬 chore, 🌩 SSOOYA

#67 #66: 마이페이지 설정 페이지 및 회원 탈퇴 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/MypageCells/Setting/AlarmSettingTableViewCell.swift
  Zatch/domain/Cells/MypageCells/Setting/DefaultSettingTableViewCell.swift
  Zatch/domain/Cells/MypageCells/Setting/SettingTitleTableViewCell.swift
  Zatch/domain/Services/KakaoDataManager/KakaoLocalDataManager.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/MapMeetingViewController.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/SearchAddressBottomSheet.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/SettingViewController.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/UserLeaveViewController.swift
  Zatch/domain/Views/MypageView/Mypage/SettingView.swift
  Zatch/domain/Views/MypageView/Mypage/UserLeaveView.swift
  Zatch/global/Source/Alert/MeetingMapAlertViewController.swift
Labels: 🎁 feat, 🌩 SSOOYA

#70 #66: 마이페이지 설정 UI 구현 및 borderLineCell 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/MypageCells/Setting/AlarmSettingTableViewCell.swift
  Zatch/domain/Cells/MypageCells/Setting/DefaultSettingTableViewCell.swift
  Zatch/domain/Cells/MypageCells/Setting/SettingBorderLineTableViewCell.swift
  Zatch/domain/Cells/MypageCells/Setting/SettingTitleTableViewCell.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/SettingViewController.swift
  Zatch/domain/Views/MypageView/Mypage/SettingView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
Labels: 🎁 feat, 🌩 SSOOYA

#73 #66, 71: 설정VC 기능 구현 및 UITableView separator style 버그 해결
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/MypageCells/Setting/AlarmSettingTableViewCell.swift
  Zatch/domain/Cells/MypageCells/Setting/SettingBorderLineTableViewCell.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/SettingViewController.swift
  Zatch/domain/Views/MypageView/Mypage/SettingView.swift
  Zatch/global/Resource/extenstion/UITableView.swift
Labels: 🎁 feat, ✏️ fix, 💎 refactor, 🌩 SSOOYA

#77 #66: 마이페이지 설정 UI 및 기능 구현
  Pods/Pods.xcodeproj/xcuserdata/vertigo.xcuserdatad/xcschemes/xcschememanagement.plist
  Zatch.xcodeproj/project.pbxproj
  Zatch.xcodeproj/xcuserdata/vertigo.xcuserdatad/xcschemes/xcschememanagement.plist
  Zatch/domain/Cells/MypageCells/Setting/AlarmSettingTableViewCell.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/SettingViewController.swift
  Zatch/global/Source/Protocol/SwitchDelegate.swift
Labels: 🎁 feat, 🌩 SSOOYA

#82 #81: CheckRegister View 파일 추가
  Pods/Pods.xcodeproj/xcuserdata/vertigo.xcuserdatad/xcschemes/xcschememanagement.plist
  Zatch.xcodeproj/project.pbxproj
  Zatch.xcodeproj/xcuserdata/vertigo.xcuserdatad/xcschemes/xcschememanagement.plist
  Zatch/domain/Views/RegisterView/CheckExchangeRegisterView.swift
  Zatch/domain/Views/RegisterView/CheckRegisterView.swift
  Zatch/domain/Views/RegisterView/CheckShareRegisterView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
Labels: 🎁 feat, 💎 refactor, 🌩 SSOOYA

#84 close #81: CheckRegisterVC 파일 분리
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Register/CheckExchangeRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/CheckRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/CheckShareRegisterViewController.swift
  Zatch/domain/Views/RegisterView/CheckRegisterView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/domain/Views/TownView/SplashTownView.swift
Labels: 🎁 feat, 💎 refactor

#87 #79, #80 issue close
  Zatch/domain/ViewControllers/Register/CheckExchangeRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/CheckRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/CheckShareRegisterViewController.swift
  Zatch/domain/Views/RegisterView/CheckExchangeRegisterView.swift
  Zatch/domain/Views/RegisterView/CheckRegisterInfoView.swift
  Zatch/domain/Views/RegisterView/CheckRegisterView.swift
  Zatch/domain/Views/RegisterView/CheckShareRegisterView.swift
  Zatch/global/Source/Alert/CancelAlertViewController.swift
Labels: 🎁 feat, 🎀 style, 💎 refactor, 🌩 SSOOYA

#89 #85, #88 issue close
  Pods/Target Support Files/Pods-ZatchTests/Pods-ZatchTests.debug.xcconfig
  Pods/Target Support Files/Pods-ZatchTests/Pods-ZatchTests.release.xcconfig
  Zatch.xcworkspace/xcuserdata/vertigo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Zatch/domain/Cells/ChattingCells/ChattingListTableViewCell.swift
  Zatch/domain/ViewControllers/Chatting/Appointment/MapMeetingViewController.swift
  Zatch/domain/ViewControllers/Chatting/ChattingRoomViewController.swift
  Zatch/domain/ViewControllers/Mypage/MyProfile/ModifyProfileViewController.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/BlockUserViewController.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/SettingViewController.swift
  Zatch/domain/ViewControllers/Register/CheckRegisterViewController.swift
  Zatch/domain/ViewControllers/Register/DeleteImageDetailViewController.swift
  Zatch/domain/ViewControllers/Register/FirstRegisterViewController.swift
  Zatch/domain/ViewControllers/Town/MapTownViewController.swift
  Zatch/domain/Views/RegisterView/CheckRegisterView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/global/Source/Alert/AlertViewController.swift
  Zatch/global/Source/Alert/CancelAlertViewController.swift
  Zatch/global/Source/Alert/DatePickerAlertViewController.swift
  Zatch/global/Source/Alert/InfoAlertViewController.swift
  Zatch/global/Source/Alert/MapAlertViewController.swift
  Zatch/global/Source/Alert/MeetingMapAlertViewController.swift
  Zatch/global/Source/Alert/PickerAlertViewController.swift
  Zatch/global/Source/Alert/TimePickerAlertViewController.swift
  Zatch/global/Source/Alert/TownMapAlertViewController.swift
  Zatch/global/Source/BaseViewController.swift
  Zatch/global/Source/Map/KakaoMapViewController.swift
Labels: 🎁 feat, 💎 refactor, 🌩 SSOOYA

#90 다른 사용자의 프로필 UI
  Zatch.xcodeproj/project.pbxproj
  Zatch.xcworkspace/xcuserdata/gomin.xcuserdatad/UserInterfaceState.xcuserstate
  Zatch/domain/Cells/MypageCells/MyPage/MyInfoTableViewCell.swift
  Zatch/domain/ViewControllers/Mypage/MyProfile/ModifyProfileViewController.swift
  Zatch/domain/ViewControllers/Mypage/MyProfile/ProfileViewController.swift
  Zatch/domain/ViewControllers/Mypage/Mypage/MypageViewController.swift
Labels: 🎁 feat, 💎 refactor

#100 #94, #95, #97 issue close 및 #99 파일 추가
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/Cells/DetailCells/ShareDetailTableViewCell.swift
  Zatch/domain/ViewControllers/Detail/DetailViewController.swift
  Zatch/domain/Views/DetailView/DetailView.swift
  Zatch/domain/Views/SearchView/FindSearchView.swift
  Zatch/domain/Views/SearchView/MySearchView.swift
  Zatch/domain/Views/SearchView/ResultSearchView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
  Zatch/global/Source/Category/CategoryBottomSheet.swift
  Zatch/global/Source/SheetViewController.swift
Labels: 🎁 feat, ✏️ fix, 🌩 SSOOYA

#101 #99: 기존 ViewController Layout 파일 제거
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Search/FindSearchViewController+Layout.swift
  Zatch/domain/ViewControllers/Search/FindSearchViewController.swift
  Zatch/domain/ViewControllers/Search/MySearchViewController+Layout.swift
  Zatch/domain/ViewControllers/Search/MySearchViewController.swift
  Zatch/domain/Views/SearchView/FindSearchView.swift
  Zatch/domain/Views/SearchView/MySearchView.swift
Labels: 💎 refactor, 🌩 SSOOYA

#102 close #99: ResultSearch View, VC 분리 및 코드 리팩토링
  Zatch.xcodeproj/project.pbxproj
  Zatch/domain/ViewControllers/Search/ResultSearchViewController+Layout.swift
  Zatch/domain/ViewControllers/Search/ResultSearchViewController.swift
  Zatch/domain/Views/SearchView/ResultSearchView.swift
Labels: 💎 refactor, 🌩 SSOOYA

#103 close #72: 차단된 사용자 없는 경우 UI 추가 및 tableViewCell separatorLine 버그 수정
  Zatch/domain/ViewControllers/Mypage/Mypage/BlockUserViewController.swift
  Zatch/domain/Views/MypageView/Mypage/BlockUserView.swift
  Zatch/domain/Views/SsooyaStoryboard.storyboard
Labels: 🎁 feat, ✏️ fix, 🌩 SSOOYA
